name: Ilk pipeline

#trigger (tetikleyici)
on:
  push: 
    branches: [ "main" ]


jobs:
  docker-login:
    name: Login to docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
#DOCKER HUB A LOGİN OL
#NOT: EGER REPOSİTORY OLARAK DOCKER HUB KULLANILACAKSA REPOSİTORY İSMİ BELİRTİLMEZ
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
